version: "3.1"
networks:
  lbarchive_network:
services:
  web:
    image: nginx:stable-alpine
    container_name: lbarchive-webserver
    depends_on:
      - php
    networks:
      - lbarchive_network
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
  php:
    image: php:7.4-fpm-alpine
    container_name: lbarchive-php
    networks:
      - lbarchive_network
    volumes:
      - .:/var/www/html
    ports:
      - "9001:9000"
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: lbarchive-elastic
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01
    networks:
      - lbarchive_network
    volumes:
      - ./index:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.1
    container_name: lbarchive-kibana
    depends_on:
      - elastic
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elastic:9200
      ELASTICSEARCH_HOSTS: '["http://elastic:9200"]'
    networks:
      - lbarchive_network
