version: "3.1"
networks:
  userauditnetwork:
services:
  web:
    image: nginx:stable-alpine
    container_name: webserver
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - php
    networks:
      - userauditnetwork
    container_name: UserAudit
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
  php:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - userauditnetwork
    container_name: php
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
  elastic:
    image:
